apiVersion: v1
kind: Namespace
metadata:
  name: player-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: player-app
  namespace: kubemq
spec:
  type: Git
  pathname: https://github.com/kubemq-io/json-streamer.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: edge
  namespace: kubemq
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      type: edge
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: player-app
  namespace: kubemq
  labels:
    app: player-app
  annotations:
    apps.open-cluster-management.io/github-path: ''
spec:
  channel: kubemq/player-app
  placement:
    placementRef:
      kind: PlacementRule
      name: edge
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: player-app
  namespace: kubemq
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - player-app
